### ISSUE TITLE
Remove Units from Display?

### ISSUE THREAD

**Issue by chrisparker787** [mykle1/MMM-PilotWX#6]
Hi,

Not an issue, but a request.

FIrst, thanks for adding mb!

Would it be possible to have an option to remove "KT" and "Hg"/"Mb" from the display?

I'd vote to keep "KM" because the numbers can be similar with "SM".

Thanks again.

**Comment by mykle1** [comment]
I had no plans to do any more modifications to this module. Really, this module represents many hours of work on my part. I do appreciate your interest. Feel free to fork the module and make any modifications you like.If you want to make the modification you mentioned above you can send a PR
